_BASE_: "../xray_Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
DATASETS:
  TRAIN: ("xray_ac_train",)
  TEST: ("xray_ac_val","xray_ac_test")
OUTPUT_DIR: /data/d2test/xray_rcnn_101_ac_00020
