_BASE_: "../xray_Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("xray_pe_train",)
  TEST: ("xray_pe_val","xray_pe_test")
OUTPUT_DIR: /data/d2test/xray_mask_rcnn_50_pe_00020
