_BASE_: "../xray_Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
OUTPUT_DIR: /data/d2test/xray_cas_rcnn_101_ac_00010
DATASETS:
  TRAIN: ("xray_ac_train",)
  TEST: ("xray_ac_val", "xray_ac_test")
