_BASE_: "../xray_Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
OUTPUT_DIR: /data/d2test/xray_cas_mask_rcnn__101_cav_00010
DATASETS:
  TRAIN: ("xray_cav_train",)
  TEST: ("xray_cav_val", "xray_cav_test")
